---
name: pokerclock
services:
  postgres:
    container_name: pokerclock
    image: postgres:latest
    restart: 'no'
    env_file: [.env]
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports: [5432:5432]
    volumes: [pgdata:/var/lib/postgresql/data]
volumes:
  pgdata:
